### ISSUE TITLE
fx102: Toolbarbutton issues

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero#3040]
I see https://github.com/zotero/zotero/blob/53ace4876e90d1e2301cae3b99b31610ae093cbc/chrome/content/zotero/elements/menuToolbarbutton.js 

Some observations:

- Button menus open when disabled in feeds (although on a related note, idk why we even show disabled buttons in feeds view instead of not showing them at all)
- I believe we don't want to display non-native menus for macOS only? If so, perhaps we want a generic solution that does not require a custom menubar element? Can we override this somehow on a global level? If not, then these menus appear in the wrong place over the buttons on Linux and maybe Windows?
- The current dropmarker solution is actually drawing two dropmarkers, one on top of another, and looks wrong on Linux. I can fix it for Linux, but it's also suboptimal, requiring a custom element type. I think we should do this type of thing with CSS where possible, and it is possible here, including the need for @2x image.
    E.g.
    ```css
    .toolbarbutton-menu-dropmarker {
      -moz-default-appearance: none;
      background-image: url("chrome://zotero/skin/searchbar-dropmarker@2x.png");
      width: 12px;
      height: 6px;
      background-repeat: no-repeat;
      background-size: 100%;
    }
    ```

Performing these two changes would eliminate the need for `menuToolbarbutton.js`.

Thoughts @AbeJellinek @dstillman ?
